import { Link } from 'react-router-dom'
import { usePageMeta } from '../hooks/usePageMeta'
import { useJsonLd } from '../hooks/useJsonLd'

const cardStyle: React.CSSProperties = { background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '14px', padding: '1.5rem' }
const wrap = { maxWidth: '1100px', margin: '0 auto', padding: '0 2rem' }

export function EmployabilityHub() {
  usePageMeta({
    title: 'Employability | Your Complete Guide to Career Readiness & Job Skills',
    description: 'Everything you need to know about employability — skills, assessment, gap analysis, career readiness, and AI-powered tools to become job-ready faster.',
    canonical: 'https://employabilityos.pages.dev/employability',
    noIndex: false,
  })
  useJsonLd({
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'WebPage',
        '@id': 'https://employabilityos.pages.dev/employability#webpage',
        'url': 'https://employabilityos.pages.dev/employability',
        'name': 'Employability | Your Complete Guide to Career Readiness & Job Skills',
        'description': 'Everything you need to know about employability — skills, assessment, gap analysis, career readiness, and AI-powered tools to become job-ready faster.',
        'isPartOf': { '@id': 'https://employabilityos.pages.dev/#website' },
        'breadcrumb': { '@type': 'BreadcrumbList', 'itemListElement': [
          { '@type': 'ListItem', 'position': 1, 'name': 'Home', 'item': 'https://employabilityos.pages.dev/' },
          { '@type': 'ListItem', 'position': 2, 'name': 'Employability', 'item': 'https://employabilityos.pages.dev/employability' },
        ]},
      },
      {
        '@type': 'ItemList',
        'name': 'Employability Resources',
        'description': 'A complete hub of employability tools, guides, and resources for students, job seekers, universities, and employers.',
        'itemListElement': [
          { '@type': 'ListItem', 'position': 1, 'name': 'Employability OS', 'url': 'https://employabilityos.pages.dev/employability-os' },
          { '@type': 'ListItem', 'position': 2, 'name': 'Employability App', 'url': 'https://employabilityos.pages.dev/employability-app' },
          { '@type': 'ListItem', 'position': 3, 'name': 'Skill-Job Gap Guide', 'url': 'https://employabilityos.pages.dev/skill-job-gap' },
        ],
      },
    ],
  })

  const topics = [
    { icon: '🖥️', title: 'Employability OS', desc: 'The complete operating system for career readiness — skill assessment, gap analysis, AI roadmap, and certification in one platform.', link: '/employability-os', cta: 'Explore Employability OS' },
    { icon: '📱', title: 'Employability App', desc: 'Our AI-powered employability app measures your skills, identifies gaps, and gives you a personalised roadmap — free for students and job seekers.', link: '/employability-app', cta: 'Get the App' },
    { icon: '📊', title: 'Skill–Job Gap', desc: 'Understand what the skill–job gap is, what causes it, how it is measured, and how to close it systematically.', link: '/skill-job-gap', cta: 'Learn About Skill Gaps' },
    { icon: '🎯', title: 'Career Readiness Assessment', desc: 'Complete the free 45-minute career readiness assessment and receive an instant AI score with a detailed skill breakdown.', link: '/signup', cta: 'Start Free Assessment' },
    { icon: '🤖', title: 'AI Learning Roadmap', desc: 'Get a personalised, prioritised learning plan generated by AI based on your exact skill gaps and target role.', link: '/signup', cta: 'Get Your Roadmap' },
    { icon: '📄', title: 'Resume Analysis', desc: 'Upload your CV and receive AI feedback on keyword alignment, structure, ATS compatibility, and improvement opportunities.', link: '/signup', cta: 'Analyse Your Resume' },
    { icon: '🎤', title: 'Interview Preparation', desc: 'Practice with AI-generated role-specific interview questions and receive real-time coaching feedback.', link: '/signup', cta: 'Practice Interviews' },
    { icon: '🏆', title: 'Skill Certification', desc: 'Earn a verified digital readiness badge and shareable PDF report to strengthen your job applications.', link: '/signup', cta: 'Get Certified' },
  ]

  const employabilitySkills = [
    { category: 'Technical Skills', examples: 'Programming, data analysis, cloud platforms, design tools, domain-specific software' },
    { category: 'Communication Skills', examples: 'Written communication, presentation, active listening, stakeholder management' },
    { category: 'Problem-Solving Skills', examples: 'Critical thinking, analytical reasoning, creative problem-solving, decision-making' },
    { category: 'Digital Literacy', examples: 'Productivity tools, collaboration platforms, basic data skills, cybersecurity awareness' },
    { category: 'Interpersonal Skills', examples: 'Teamwork, emotional intelligence, conflict resolution, cross-cultural collaboration' },
    { category: 'Self-Management Skills', examples: 'Time management, resilience, adaptability, continuous learning mindset' },
    { category: 'Commercial Awareness', examples: 'Understanding of industry, business models, market trends, employer context' },
    { category: 'Project Management', examples: 'Planning, delivery, stakeholder communication, risk management, agile/scrum basics' },
  ]

  return (
    <main id="main-content" style={{ background: '#0a0a0f', minHeight: '100vh', color: '#e2e8f0', fontFamily: 'Inter, sans-serif' }}>
      <nav aria-label="Breadcrumb" style={{ ...wrap, paddingTop: '1.5rem', paddingBottom: 0, fontSize: '0.85rem', color: '#64748b' }}>
        <Link to="/" style={{ color: '#7c3aed', textDecoration: 'none' }}>Home</Link>
        <span style={{ margin: '0 0.5rem' }}>›</span>
        <span>Employability</span>
      </nav>

      {/* Hero */}
      <section style={{ ...wrap, padding: '4rem 2rem 3rem', textAlign: 'center' }}>
        <div style={{ display: 'inline-block', background: 'rgba(124,58,237,0.15)', border: '1px solid rgba(124,58,237,0.3)', borderRadius: '999px', padding: '0.4rem 1.2rem', fontSize: '0.82rem', color: '#a78bfa', marginBottom: '1.5rem', fontWeight: 500 }}>Employability Hub</div>
        <h1 style={{ fontSize: 'clamp(1.8rem, 4vw, 3rem)', fontWeight: 800, lineHeight: 1.15, marginBottom: '1.5rem', background: 'linear-gradient(135deg, #fff 0%, #a78bfa 100%)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>
          Employability — Your Complete Career Readiness Resource
        </h1>
        <p style={{ fontSize: '1.1rem', lineHeight: 1.75, color: '#94a3b8', maxWidth: '700px', margin: '0 auto 2rem' }}>
          <strong style={{ color: '#e2e8f0' }}>Employability</strong> is the combination of skills, knowledge, attitudes, and experiences that make a person competitive in the job market. This hub covers everything you need to understand, measure, and improve your employability — from definitions to tools to action plans.
        </p>
        <Link to="/signup" style={{ display: 'inline-block', background: 'linear-gradient(135deg, #7c3aed, #2563eb)', color: '#fff', padding: '0.85rem 2rem', borderRadius: '10px', textDecoration: 'none', fontWeight: 700 }}>Measure Your Employability Free →</Link>
      </section>

      {/* Definition block */}
      <section style={{ ...wrap, maxWidth: '900px', marginBottom: '4rem' }}>
        <div style={{ background: 'rgba(124,58,237,0.08)', border: '1px solid rgba(124,58,237,0.25)', borderRadius: '16px', padding: '2rem' }}>
          <h2 style={{ fontSize: '1.25rem', fontWeight: 700, marginBottom: '1rem', color: '#fff' }}>What is Employability?</h2>
          <p style={{ lineHeight: 1.8, color: '#cbd5e1', fontSize: '1.05rem', marginBottom: '1rem' }}>
            <strong style={{ color: '#a78bfa' }}>Employability</strong> refers to the portable skills, attributes, and experiences that make an individual attractive to employers, capable of performing effectively in the workplace, and able to adapt as the job market evolves. It goes beyond academic qualifications to include practical skills, professional behaviours, digital literacy, communication ability, and demonstrated experience.
          </p>
          <p style={{ lineHeight: 1.8, color: '#cbd5e1', fontSize: '1.05rem' }}>
            High employability means you can not only <em>get</em> a job, but <em>perform</em> effectively in it and <em>adapt</em> as requirements change. Low employability often means there is a measurable skill–job gap between what you currently offer and what employers require.
          </p>
        </div>
      </section>

      {/* Topic hub grid */}
      <section style={{ ...wrap, marginBottom: '5rem' }}>
        <h2 style={{ fontSize: '1.8rem', fontWeight: 800, textAlign: 'center', marginBottom: '0.75rem', color: '#fff' }}>Explore Every Aspect of Employability</h2>
        <p style={{ textAlign: 'center', color: '#94a3b8', marginBottom: '2.5rem' }}>Deep-dive resources for every stage of your career readiness journey</p>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: '1.25rem' }}>
          {topics.map(t => (
            <div key={t.title} style={{ ...cardStyle, display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
              <div style={{ fontSize: '2rem' }}>{t.icon}</div>
              <h3 style={{ fontWeight: 700, color: '#fff', fontSize: '1rem', margin: 0 }}>{t.title}</h3>
              <p style={{ fontSize: '0.87rem', color: '#94a3b8', lineHeight: 1.65, margin: 0, flex: 1 }}>{t.desc}</p>
              <Link to={t.link} style={{ display: 'inline-block', color: '#a78bfa', fontSize: '0.87rem', fontWeight: 600, textDecoration: 'none' }}>{t.cta} →</Link>
            </div>
          ))}
        </div>
      </section>

      {/* Core employability skills */}
      <section style={{ ...wrap, maxWidth: '900px', marginBottom: '5rem' }}>
        <h2 style={{ fontSize: '1.8rem', fontWeight: 800, textAlign: 'center', marginBottom: '0.75rem', color: '#fff' }}>Core Employability Skills</h2>
        <p style={{ textAlign: 'center', color: '#94a3b8', marginBottom: '2.5rem' }}>The 8 skill categories employers consistently rank highest in hiring decisions</p>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
          {employabilitySkills.map((s, i) => (
            <div key={s.category} style={{ ...cardStyle, display: 'flex', gap: '1rem', alignItems: 'flex-start', padding: '1.1rem 1.5rem' }}>
              <div style={{ width: '28px', height: '28px', borderRadius: '50%', background: 'rgba(124,58,237,0.2)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 800, color: '#7c3aed', flexShrink: 0, fontSize: '0.8rem' }}>{i + 1}</div>
              <div>
                <h3 style={{ fontWeight: 700, color: '#fff', fontSize: '0.95rem', marginBottom: '0.3rem' }}>{s.category}</h3>
                <p style={{ fontSize: '0.85rem', color: '#94a3b8', margin: 0, lineHeight: 1.5 }}>{s.examples}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Employability vs qualification */}
      <section style={{ ...wrap, maxWidth: '860px', marginBottom: '5rem' }}>
        <h2 style={{ fontSize: '1.8rem', fontWeight: 800, textAlign: 'center', marginBottom: '2rem', color: '#fff' }}>Employability vs. Qualifications — What Employers Actually Want</h2>
        <div style={{ overflowX: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.93rem' }}>
            <thead>
              <tr style={{ background: 'rgba(124,58,237,0.12)' }}>
                {['Dimension', 'Qualifications Alone', 'Strong Employability'].map(h => (
                  <th key={h} style={{ padding: '0.9rem 1rem', textAlign: h === 'Dimension' ? 'left' : 'center', color: h === 'Qualifications Alone' ? '#64748b' : '#a78bfa', fontWeight: 700, borderBottom: '1px solid rgba(255,255,255,0.08)' }}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {[
                ['Job Interview Success', '⚠️ Variable', '✅ High — skills are demonstrable'],
                ['Salary Negotiation', '⚠️ Based on grade/credential', '✅ Based on proven capabilities'],
                ['Time to Employment', '⚠️ Often 6+ months', '✅ Typically faster with skill signals'],
                ['Career Adaptability', '⚠️ Locked to one field', '✅ Transferable across roles'],
                ['Employer Confidence', '⚠️ Based on institution name', '✅ Based on verified competency'],
              ].map(([d, q, e], i) => (
                <tr key={d} style={{ background: i % 2 === 0 ? 'rgba(255,255,255,0.01)' : 'transparent' }}>
                  <td style={{ padding: '0.8rem 1rem', color: '#cbd5e1', borderBottom: '1px solid rgba(255,255,255,0.05)' }}>{d}</td>
                  <td style={{ padding: '0.8rem 1rem', textAlign: 'center', color: '#94a3b8', borderBottom: '1px solid rgba(255,255,255,0.05)' }}>{q}</td>
                  <td style={{ padding: '0.8rem 1rem', textAlign: 'center', color: '#4ade80', borderBottom: '1px solid rgba(255,255,255,0.05)', fontWeight: 600 }}>{e}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      {/* Quick links to all related pages */}
      <section style={{ ...wrap, maxWidth: '860px', marginBottom: '5rem' }}>
        <h2 style={{ fontSize: '1.5rem', fontWeight: 800, textAlign: 'center', marginBottom: '1.5rem', color: '#fff' }}>Related Resources</h2>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.75rem', justifyContent: 'center' }}>
          {[
            { label: 'Employability OS', to: '/employability-os' },
            { label: 'Employability App', to: '/employability-app' },
            { label: 'Skill–Job Gap Guide', to: '/skill-job-gap' },
            { label: 'Start Free Assessment', to: '/signup' },
            { label: 'Privacy Policy', to: '/privacy' },
            { label: 'Terms of Service', to: '/terms' },
          ].map(l => (
            <Link key={l.to} to={l.to} style={{ display: 'inline-block', background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.1)', color: '#a78bfa', padding: '0.5rem 1.2rem', borderRadius: '999px', textDecoration: 'none', fontSize: '0.88rem', fontWeight: 500 }}>{l.label}</Link>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section style={{ ...wrap, maxWidth: '860px', marginBottom: '5rem' }}>
        <div style={{ background: 'linear-gradient(135deg, rgba(124,58,237,0.2), rgba(37,99,235,0.15))', border: '1px solid rgba(124,58,237,0.3)', borderRadius: '20px', padding: '3rem 2rem', textAlign: 'center' }}>
          <h2 style={{ fontSize: '1.7rem', fontWeight: 800, color: '#fff', marginBottom: '1rem' }}>Start Building Your Employability Today</h2>
          <p style={{ color: '#94a3b8', marginBottom: '2rem' }}>Free assessment. Instant AI gap score. Personalised roadmap. No credit card required.</p>
          <Link to="/signup" style={{ display: 'inline-block', background: 'linear-gradient(135deg, #7c3aed, #2563eb)', color: '#fff', padding: '1rem 2.5rem', borderRadius: '10px', textDecoration: 'none', fontWeight: 700, fontSize: '1rem' }}>Get Your Free Employability Score →</Link>
        </div>
      </section>
    </main>
  )
}
