import { useState } from 'react'
import { Link } from 'react-router-dom'
import { usePageMeta } from '../hooks/usePageMeta'
import { useJsonLd } from '../hooks/useJsonLd'

const cardStyle: React.CSSProperties = { background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '14px', padding: '1.5rem' }
const wrap = { maxWidth: '1100px', margin: '0 auto', padding: '0 2rem' }

export function EmployabilityApp() {
  usePageMeta({
    title: 'Employability App | AI Career Readiness App for Students & Job Seekers',
    description: 'The Employability App that measures your skills, identifies job gaps, and gives you a personalised AI roadmap. Free for students, job seekers, universities, and employers.',
    canonical: 'https://employability-os-or-skill-job-gap.vercel.app/employability-app',
    noIndex: false,
  })
  useJsonLd({
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'WebPage',
        '@id': 'https://employability-os-or-skill-job-gap.vercel.app/employability-app#webpage',
        'url': 'https://employability-os-or-skill-job-gap.vercel.app/employability-app',
        'name': 'Employability App | AI Career Readiness App for Students & Job Seekers',
        'description': 'The Employability App that measures your skills, identifies job gaps, and gives you a personalised AI roadmap. Free for students, job seekers, universities, and employers.',
        'isPartOf': { '@id': 'https://employability-os-or-skill-job-gap.vercel.app/#website' },
        'breadcrumb': { '@type': 'BreadcrumbList', 'itemListElement': [
          { '@type': 'ListItem', 'position': 1, 'name': 'Home', 'item': 'https://employability-os-or-skill-job-gap.vercel.app/' },
          { '@type': 'ListItem', 'position': 2, 'name': 'Employability App', 'item': 'https://employability-os-or-skill-job-gap.vercel.app/employability-app' },
        ]},
      },
      {
        '@type': 'FAQPage',
        'mainEntity': [
          { '@type': 'Question', 'name': 'What is an employability app?', 'acceptedAnswer': { '@type': 'Answer', 'text': 'An employability app is a digital tool that helps individuals understand, measure, and improve their readiness for employment. The best employability apps assess your actual skill profile, benchmark it against employer requirements, identify your specific gaps, and provide a structured path to close them.' } },
          { '@type': 'Question', 'name': 'Who is the employability app for?', 'acceptedAnswer': { '@type': 'Answer', 'text': 'The app is designed for students and graduates, job seekers who want a data-backed assessment of their readiness, career changers identifying new role requirements, and universities tracking graduate employability outcomes.' } },
          { '@type': 'Question', 'name': 'Is the employability app free?', 'acceptedAnswer': { '@type': 'Answer', 'text': 'Yes. The core features — including the full skill gap assessment, gap score, employability score, and personalised feedback — are completely free. Advanced tools are available to registered users at no initial cost.' } },
          { '@type': 'Question', 'name': 'How does the employability app differ from a job board?', 'acceptedAnswer': { '@type': 'Answer', 'text': 'Job boards show you what roles are available. Our employability app tells you whether you are ready for those roles and exactly what to do if you are not, replacing speculative applications with systematic skill building.' } },
          { '@type': 'Question', 'name': 'Can universities use this employability app?', 'acceptedAnswer': { '@type': 'Answer', 'text': 'Yes. Universities can access an institution dashboard showing cohort-level employability data, programme-specific gap reports, and graduate readiness trends for accreditation and employer engagement activities.' } },
        ],
      },
    ],
  })
  const [open, setOpen] = useState<number | null>(null)

  const features = [
    { icon: '📊', title: 'Skill Gap Analysis', desc: 'Measure your current skills against real employer benchmarks and get a precise gap score (0–100) for each competency area.' },
    { icon: '🤖', title: 'AI Learning Roadmap', desc: 'Get a personalised, prioritised learning plan generated by AI based on your exact gaps and your target role or industry.' },
    { icon: '📄', title: 'Resume Analyser', desc: 'Upload your CV and receive instant AI feedback on keyword alignment, structure, ATS compatibility, and improvement opportunities.' },
    { icon: '🎤', title: 'Interview Preparation', desc: 'Practice with AI-generated role-specific interview questions, get real-time feedback, and track your confidence improvement.' },
    { icon: '🏆', title: 'Skill Certification Badge', desc: 'Earn a verified digital readiness badge and a shareable PDF report you can attach to job applications and LinkedIn.' },
    { icon: '📈', title: 'Progress Tracking', desc: 'Track your employability score improvement over time across all five dimensions as you complete your learning roadmap.' },
    { icon: '🔍', title: 'Job Role Benchmarking', desc: 'Compare your profile against requirements for specific roles — software engineer, product manager, data analyst, and more.' },
    { icon: '🏫', title: 'University Dashboard', desc: 'Institutions can track cohort-level employability scores, identify programme gaps, and demonstrate graduate outcomes.' },
  ]

  const faqs = [
    { q: 'What is an employability app?', a: 'An employability app is a digital tool that helps individuals understand, measure, and improve their readiness for employment. The best employability apps go beyond job listings — they assess your actual skill profile, benchmark it against employer requirements, identify your specific gaps, and provide a structured path to close them. Our Employability App does all of this using AI.' },
    { q: 'Who is this employability app designed for?', a: 'The app is designed for: (1) Students and graduates who want to understand what employers expect and how to meet those expectations; (2) Job seekers at any career stage who want a data-backed assessment of their readiness; (3) Career changers who need to identify which skills to build for a new role; and (4) Universities and training providers who want to track and report on graduate employability outcomes.' },
    { q: 'Is the employability app free?', a: 'Yes. The core features — including the full skill gap assessment, gap score, employability score, and personalised feedback — are completely free. Advanced tools like AI roadmap generation, resume analysis, and interview preparation are available to registered users at no initial cost.' },
    { q: 'How does the employability app differ from a job board?', a: 'Job boards show you what roles are available. Our employability app tells you whether you are ready for those roles — and exactly what to do if you are not. Instead of sending speculative applications, you use the app to systematically build the skills employers actually require for your target role.' },
    { q: 'Can universities use this employability app?', a: 'Yes. Universities and training providers can access an institution dashboard showing cohort-level employability data, programme-specific gap reports, and graduate readiness trends. This data can support accreditation, quality assurance, and employer engagement activities.' },
    { q: 'What skills does the employability app assess?', a: 'The app assesses skills across five dimensions: Technical Skills (programming, tools, domain knowledge), Project Experience (portfolio quality, complexity, relevance), Communication & Soft Skills (writing, teamwork, problem-solving), Resume Quality (structure, keywords, ATS alignment), and Interview Readiness (confidence, STAR responses, role knowledge).' },
  ]

  return (
    <main id="main-content" style={{ background: '#0a0a0f', minHeight: '100vh', color: '#e2e8f0', fontFamily: 'Inter, sans-serif' }}>
      <nav aria-label="Breadcrumb" style={{ ...wrap, paddingTop: '1.5rem', paddingBottom: 0, fontSize: '0.85rem', color: '#64748b' }}>
        <Link to="/" style={{ color: '#7c3aed', textDecoration: 'none' }}>Home</Link>
        <span style={{ margin: '0 0.5rem' }}>›</span>
        <span>Employability App</span>
      </nav>

      {/* Hero */}
      <section style={{ ...wrap, padding: '4rem 2rem 3rem', textAlign: 'center' }}>
        <div style={{ display: 'inline-block', background: 'rgba(124,58,237,0.15)', border: '1px solid rgba(124,58,237,0.3)', borderRadius: '999px', padding: '0.4rem 1.2rem', fontSize: '0.82rem', color: '#a78bfa', marginBottom: '1.5rem', fontWeight: 500 }}>Free Employability App</div>
        <h1 style={{ fontSize: 'clamp(1.8rem, 4vw, 3rem)', fontWeight: 800, lineHeight: 1.15, marginBottom: '1.5rem', background: 'linear-gradient(135deg, #fff 0%, #a78bfa 100%)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>
          The Employability App That Tells You Exactly Where You Stand
        </h1>
        <p style={{ fontSize: '1.1rem', lineHeight: 1.75, color: '#94a3b8', maxWidth: '700px', margin: '0 auto 2rem' }}>
          Stop guessing why applications fail. Our <strong style={{ color: '#e2e8f0' }}>employability app</strong> measures your skills against real employer benchmarks, shows you your exact gaps, and builds an AI-powered roadmap to close them — free for students and job seekers.
        </p>
        <div style={{ display: 'flex', gap: '1rem', justifyContent: 'center', flexWrap: 'wrap' }}>
          <Link to="/signup" style={{ display: 'inline-block', background: 'linear-gradient(135deg, #7c3aed, #2563eb)', color: '#fff', padding: '0.85rem 2rem', borderRadius: '10px', textDecoration: 'none', fontWeight: 700 }}>Get Your Free Employability Score →</Link>
          <Link to="/employability-os" style={{ display: 'inline-block', background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.12)', color: '#e2e8f0', padding: '0.85rem 2rem', borderRadius: '10px', textDecoration: 'none', fontWeight: 600 }}>About Employability OS</Link>
        </div>
        <p style={{ marginTop: '1.5rem', fontSize: '0.85rem', color: '#64748b' }}>🎓 For students · 💼 For job seekers · 🏫 For universities · 🏢 For employers</p>
      </section>

      {/* AEO Answer block */}
      <section style={{ ...wrap, maxWidth: '900px', marginBottom: '4rem' }}>
        <div style={{ background: 'rgba(124,58,237,0.08)', border: '1px solid rgba(124,58,237,0.25)', borderRadius: '16px', padding: '2rem' }}>
          <h2 style={{ fontSize: '1.25rem', fontWeight: 700, marginBottom: '1rem', color: '#fff' }}>What is the Employability App?</h2>
          <p style={{ lineHeight: 1.8, color: '#cbd5e1', fontSize: '1rem' }}>
            The <strong style={{ color: '#a78bfa' }}>Employability App</strong> (part of Employability OS) is an AI-powered career readiness platform that measures your actual skills against employer requirements, generates a precise skill gap score, and provides a personalised learning roadmap to close those gaps. Unlike a job board or CV tool, it focuses on building your real job readiness — not just presenting your existing profile. It is free to use for students, graduates, and job seekers.
          </p>
        </div>
      </section>

      {/* Features */}
      <section style={{ ...wrap, marginBottom: '5rem' }}>
        <h2 style={{ fontSize: '1.8rem', fontWeight: 800, textAlign: 'center', marginBottom: '0.75rem', color: '#fff' }}>Core Features of the Employability App</h2>
        <p style={{ textAlign: 'center', color: '#94a3b8', marginBottom: '2.5rem' }}>Everything you need to go from skill gaps to job-ready — in one platform</p>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: '1.25rem' }}>
          {features.map(f => (
            <div key={f.title} style={cardStyle}>
              <div style={{ fontSize: '2rem', marginBottom: '0.75rem' }}>{f.icon}</div>
              <h3 style={{ fontWeight: 700, color: '#fff', marginBottom: '0.5rem', fontSize: '1rem' }}>{f.title}</h3>
              <p style={{ fontSize: '0.88rem', color: '#94a3b8', lineHeight: 1.65 }}>{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* User workflow */}
      <section style={{ ...wrap, marginBottom: '5rem' }}>
        <h2 style={{ fontSize: '1.8rem', fontWeight: 800, textAlign: 'center', marginBottom: '0.75rem', color: '#fff' }}>How to Use the Employability App</h2>
        <p style={{ textAlign: 'center', color: '#94a3b8', marginBottom: '2.5rem' }}>From sign-up to job-ready in 4 steps</p>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '1.25rem' }}>
          {[
            { num: '1', title: 'Create a Free Account', desc: 'Sign up in under 60 seconds. No credit card. Select your target role or industry.' },
            { num: '2', title: 'Complete Your Assessment', desc: 'Work through the 45-minute competency evaluation at your own pace.' },
            { num: '3', title: 'Get Your Employability Score', desc: 'Receive an instant AI-generated score with a breakdown of strengths and gaps by skill area.' },
            { num: '4', title: 'Follow Your Roadmap', desc: 'Work through your personalised learning plan, build projects, and earn your verified readiness badge.' },
          ].map(s => (
            <div key={s.num} style={{ ...cardStyle, display: 'flex', gap: '1rem' }}>
              <div style={{ width: '36px', height: '36px', borderRadius: '50%', background: 'linear-gradient(135deg, #7c3aed, #2563eb)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 800, color: '#fff', flexShrink: 0, fontSize: '0.9rem' }}>{s.num}</div>
              <div>
                <h3 style={{ fontWeight: 700, color: '#fff', marginBottom: '0.4rem', fontSize: '0.97rem' }}>{s.title}</h3>
                <p style={{ fontSize: '0.87rem', color: '#94a3b8', lineHeight: 1.6 }}>{s.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Audience tabs */}
      <section style={{ ...wrap, maxWidth: '900px', marginBottom: '5rem' }}>
        <h2 style={{ fontSize: '1.8rem', fontWeight: 800, textAlign: 'center', marginBottom: '2.5rem', color: '#fff' }}>Built for Every Employability Journey</h2>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '1.25rem' }}>
          {[
            { title: 'For Students', icon: '🎓', points: ['Map your academic skills to employer needs', 'Identify gaps before graduation', 'Build a portfolio while studying', 'Graduate with a verified readiness certificate'] },
            { title: 'For Job Seekers', icon: '💼', points: ['Understand why applications are rejected', 'Build targeted skills for specific roles', 'Improve resume ATS compatibility', 'Practice interviews with AI feedback'] },
            { title: 'For Universities', icon: '🏫', points: ['Track student employability outcomes', 'Report on programme-level skill readiness', 'Demonstrate value to employers & accreditors', 'Identify curriculum improvement opportunities'] },
            { title: 'For Employers', icon: '🏢', points: ['Pre-screen candidates by readiness score', 'Set minimum skill thresholds per role', 'Reduce mis-hire risk with objective data', 'Build a pipeline of assessed candidates'] },
          ].map(a => (
            <div key={a.title} style={cardStyle}>
              <div style={{ fontSize: '2rem', marginBottom: '0.75rem' }}>{a.icon}</div>
              <h3 style={{ fontWeight: 700, color: '#fff', marginBottom: '0.75rem', fontSize: '1rem' }}>{a.title}</h3>
              <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: '0.45rem' }}>
                {a.points.map(p => <li key={p} style={{ fontSize: '0.85rem', color: '#94a3b8', display: 'flex', gap: '0.4rem' }}><span style={{ color: '#7c3aed' }}>✓</span>{p}</li>)}
              </ul>
            </div>
          ))}
        </div>
      </section>

      {/* FAQ */}
      <section style={{ ...wrap, maxWidth: '800px', marginBottom: '5rem' }}>
        <h2 style={{ fontSize: '1.8rem', fontWeight: 800, textAlign: 'center', marginBottom: '2.5rem', color: '#fff' }}>Employability App — FAQ</h2>
        <dl>
          {faqs.map((faq, i) => (
            <div key={i} style={{ borderBottom: '1px solid rgba(255,255,255,0.08)' }}>
              <dt>
                <button onClick={() => setOpen(open === i ? null : i)} aria-expanded={open === i} style={{ width: '100%', background: 'none', border: 'none', cursor: 'pointer', display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '1.1rem 0', textAlign: 'left', color: '#e2e8f0', fontSize: '0.97rem', fontWeight: 600, fontFamily: 'Inter, sans-serif' }}>
                  {faq.q}
                  <span style={{ flexShrink: 0, marginLeft: '1rem', color: '#7c3aed', transform: open === i ? 'rotate(45deg)' : 'none', transition: 'transform 0.2s', fontSize: '1.3rem', fontWeight: 400 }}>+</span>
                </button>
              </dt>
              {open === i && <dd style={{ margin: 0, padding: '0 0 1.1rem', color: '#94a3b8', lineHeight: 1.75, fontSize: '0.93rem' }}>{faq.a}</dd>}
            </div>
          ))}
        </dl>
      </section>

      {/* CTA */}
      <section style={{ ...wrap, maxWidth: '860px', marginBottom: '5rem' }}>
        <div style={{ background: 'linear-gradient(135deg, rgba(124,58,237,0.2), rgba(37,99,235,0.15))', border: '1px solid rgba(124,58,237,0.3)', borderRadius: '20px', padding: '3rem 2rem', textAlign: 'center' }}>
          <h2 style={{ fontSize: '1.7rem', fontWeight: 800, color: '#fff', marginBottom: '1rem' }}>Download Your Employability Score Today</h2>
          <p style={{ color: '#94a3b8', marginBottom: '2rem', maxWidth: '560px', margin: '0 auto 2rem' }}>Start free. No credit card needed. Get your full skill gap breakdown, employability score, and personalised roadmap in under an hour.</p>
          <Link to="/signup" style={{ display: 'inline-block', background: 'linear-gradient(135deg, #7c3aed, #2563eb)', color: '#fff', padding: '1rem 2.5rem', borderRadius: '10px', textDecoration: 'none', fontWeight: 700, fontSize: '1rem' }}>Start Free Assessment →</Link>
          <p style={{ marginTop: '1rem', fontSize: '0.85rem', color: '#64748b' }}>
            Also see: <Link to="/employability-os" style={{ color: '#7c3aed', textDecoration: 'none' }}>Employability OS</Link> · <Link to="/skill-job-gap" style={{ color: '#7c3aed', textDecoration: 'none' }}>Skill–Job Gap</Link> · <Link to="/employability" style={{ color: '#7c3aed', textDecoration: 'none' }}>Employability Hub</Link>
          </p>
        </div>
      </section>
    </main>
  )
}
